export enum StencilType {
    DEFAULT_STENCIL = 'DEFAULT_STENCIL',
    SHIPPING_ADDRESS = 'SHIPPING_ADDRESS',
    SHIPPING_ADDRESS_PICKER = 'SHIPPING_ADDRESS_PICKER',
    SHIPPING_METHOD = 'SHIPPING_METHOD',
    PAYMENT = 'PAYMENT',
}
