import { CART_ITEM_FALLBACK_IMAGE_URL } from './constants';
import type { CartItemData } from 'commerce_data_provider/cartDataProvider';

export const sampleCartItemData: CartItemData[] = [
    {
        id: '0a9xx00000007pVAAQ',
        name: 'BigfootBar Blueberry/Pistacio Paleo, 2oz bar - 6 pack',
        quantity: 9,
        type: 'Product',
        salesPrice: 22.5,
        adjustmentAmount: -13.5,
        amount: 189,
        listPrice: 202.5,
        price: 189,
        tax: 0,
        unitAdjustedPrice: 22.5,
        unitAdjustmentAmount: 0,
        ProductDetails: {
            name: 'BigfootBar Blueberry/Pistacio Paleo, 2oz bar - 6 pack',
            fields: {
                DisplayUrl: null,
                Description: "Alpine's Bigfootbar is no hoax. The energy bar that tastes light.",
                ProductCode: '6010045',
                QuantityUnitOfMeasure: null,
                Family: null,
            },
            purchaseQuantityRule: undefined,
            sku: '6010045',
            thumbnailImage: {
                alternateText: '',
                contentVersionId: null,
                id: null,
                mediaType: 'Image',
                sortOrder: 0,
                thumbnailUrl: null,
                title: 'image',
                url: CART_ITEM_FALLBACK_IMAGE_URL,
            },
            productId: '01txx0000006lwVAAQ',
            variationAttributes: {},
        },
    },
    {
        id: '0a9xx00000007mHAAQ',
        name: 'GoBrew Moca MCT + Protein Vegetarian, 6 oz can - 6 pack',
        quantity: 3,
        type: 'Product',
        salesPrice: 13.99,
        adjustmentAmount: 0,
        amount: 41.97,
        listPrice: 59.97,
        price: 41.97,
        tax: 0,
        unitAdjustedPrice: 13.99,
        unitAdjustmentAmount: 0,
        ProductDetails: {
            name: 'GoBrew Moca MCT + Protein Vegetarian, 6 oz can - 6 pack',
            fields: {
                DisplayUrl: null,
                Description: 'Alpine Blends GoBrew Mocha Coffee in 6 oz can.',
                ProductCode: '6010006',
                QuantityUnitOfMeasure: null,
                Family: null,
            },
            purchaseQuantityRule: undefined,
            sku: '6010006',
            thumbnailImage: {
                alternateText: '',
                contentVersionId: null,
                id: null,
                mediaType: 'Image',
                sortOrder: 0,
                thumbnailUrl: null,
                title: 'image',
                url: CART_ITEM_FALLBACK_IMAGE_URL,
            },
            productId: '01txx0000006lwQAAQ',
            variationAttributes: {
                attributes: [
                    {
                        label: 'Flavor',
                        value: 'Chocolate',
                        apiName: 'flavor',
                        sequence: 1,
                    },
                    {
                        label: 'Size',
                        value: '500mL',
                        apiName: 'size',
                        sequence: 1,
                    },
                ],
            },
        },
    },
];
