/*
 * Copyright (c) 2025, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * For full license text, see the LICENSE file in the repo
 * root or https://opensource.org/licenses/apache-2-0/
 */
export const LABEL_DATA = {
    confirmationTitle: {
        en_US: 'Your order is confirmed.',
        en_GB: 'Your order is confirmed.',
        en: 'Your order is confirmed.',
        de: 'Ihre Bestellung ist bestätigt.',
        es: 'Tu pedido está confirmado.',
        fr: 'Votre commande est confirmée.',
        it: 'Il tuo ordine è confermato.',
        ja: 'ご注文が確定しました。',
        ko: '주문이 확인되었습니다.',
        nl: 'Je bestelling is bevestigd.',
        no: 'Bestillingen din er bekreftet.',
        pl: 'Twoje zamówienie zostało potwierdzone.',
        pt_BR: 'Seu pedido foi confirmado.',
        sv: 'Din beställning är bekräftad.',
        da: 'Din ordre er bekræftet.',
        fi: 'Tilauksesi on vahvistettu.',
        zh_CN: '您的订单已确认。',
        zh_TW: '您的訂單已確認。',
    },

    subtotalLabel: {
        en_US: 'Subtotal',
        en_GB: 'Subtotal',
        en: 'Subtotal',
        de: 'Zwischensumme',
        es: 'Subtotal',
        fr: 'Sous-total',
        it: 'Subtotale',
        ja: '小計',
        ko: '소계',
        nl: 'Subtotaal',
        no: 'Delsum',
        pl: 'Suma częściowa',
        pt_BR: 'Subtotal',
        sv: 'Delsumma',
        da: 'Delsum',
        fi: 'Välisumma',
        zh_CN: '小计',
        zh_TW: '小計',
    },

    promotionsLabel: {
        en_US: 'Promotions',
        en_GB: 'Promotions',
        en: 'Promotions',
        de: 'Rabatte',
        es: 'Promociones',
        fr: 'Promotions',
        it: 'Promozioni',
        ja: 'プロモーション',
        ko: '프로모션',
        nl: 'Promoties',
        no: 'Rabatter',
        pl: 'Promocje',
        pt_BR: 'Promoções',
        sv: 'Rabatter',
        da: 'Kampagner',
        fi: 'Kampanjat',
        zh_CN: '优惠',
        zh_TW: '優惠',
    },

    shippingLabel: {
        en_US: 'Shipping',
        en_GB: 'Shipping',
        en: 'Shipping',
        de: 'Versand',
        es: 'Envío',
        fr: 'Livraison',
        it: 'Spedizione',
        ja: '送料',
        ko: '배송',
        nl: 'Verzending',
        no: 'Frakt',
        pl: 'Wysyłka',
        pt_BR: 'Frete',
        sv: 'Frakt',
        da: 'Fragt',
        fi: 'Toimitus',
        zh_CN: '配送',
        zh_TW: '運送',
    },

    shippingDiscountLabel: {
        en_US: 'Shipping Discount',
        en_GB: 'Shipping Discount',
        en: 'Shipping Discount',
        de: 'Versandrabatt',
        es: 'Descuento de envío',
        fr: 'Remise sur la livraison',
        it: 'Sconto sulla spedizione',
        ja: '送料割引',
        ko: '배송 할인',
        nl: 'Korting op verzending',
        no: 'Fraktrabatt',
        pl: 'Zniżka na wysyłkę',
        pt_BR: 'Desconto no frete',
        sv: 'Fraktrabatt',
        da: 'Fragtrabat',
        fi: 'Toimitusalennus',
        zh_CN: '运费折扣',
        zh_TW: '運費折扣',
    },

    taxesLabel: {
        en_US: 'Taxes',
        en_GB: 'Taxes',
        en: 'Taxes',
        de: 'Steuern',
        es: 'Impuestos',
        fr: 'Taxes',
        it: 'Tasse',
        ja: '税金',
        ko: '세금',
        nl: 'Belastingen',
        no: 'Avgifter',
        pl: 'Podatki',
        pt_BR: 'Impostos',
        sv: 'Skatter',
        da: 'Skatter',
        fi: 'Verot',
        zh_CN: '税费',
        zh_TW: '稅費',
    },

    totalLabel: {
        en_US: 'Total',
        en_GB: 'Total',
        en: 'Total',
        de: 'Gesamt',
        es: 'Total',
        fr: 'Total',
        it: 'Totale',
        ja: '合計',
        ko: '합계',
        nl: 'Totaal',
        no: 'Totalt',
        pl: 'Razem',
        pt_BR: 'Total',
        sv: 'Totalt',
        da: 'I alt',
        fi: 'Yhteensä',
        zh_CN: '合计',
        zh_TW: '合計',
    },

    tbdLabel: {
        en_US: 'TBD',
        en_GB: 'TBD',
        en: 'TBD',
        de: 'Wird noch festgelegt',
        es: 'Por determinar',
        fr: 'À déterminer',
        it: 'Da definire',
        ja: '未定',
        ko: '추후 결정',
        nl: 'Nader te bepalen',
        no: 'Avklares',
        pl: 'Do ustalenia',
        pt_BR: 'A definir',
        sv: 'Fastställs senare',
        da: 'Afgøres senere',
        fi: 'Määritetään myöhemmin',
        zh_CN: '待定',
        zh_TW: '待定',
    },

    freeShippingLabel: {
        en_US: 'Free',
        en_GB: 'Free',
        en: 'Free',
        de: 'Kostenlos',
        es: 'Gratis',
        fr: 'Gratuit',
        it: 'Gratuito',
        ja: '無料',
        ko: '무료',
        nl: 'Gratis',
        no: 'Gratis',
        pl: 'Bezpłatnie',
        pt_BR: 'Grátis',
        sv: 'Gratis',
        da: 'Gratis',
        fi: 'Ilmainen',
        zh_CN: '免费',
        zh_TW: '免費',
    },

    defaultDeliveryMessage: {
        en_US: 'Your order is confirmed.',
        en_GB: 'Your order is confirmed.',
        en: 'Your order is confirmed.',
        de: 'Ihre Bestellung ist bestätigt.',
        es: 'Tu pedido está confirmado.',
        fr: 'Votre commande est confirmée.',
        it: 'Il tuo ordine è confermato.',
        ja: 'ご注文が確定しました。',
        ko: '주문이 확인되었습니다.',
        nl: 'Je bestelling is bevestigd.',
        no: 'Bestillingen din er bekreftet.',
        pl: 'Twoje zamówienie zostało potwierdzone.',
        pt_BR: 'Seu pedido foi confirmado.',
        sv: 'Din beställning är bekräftad.',
        da: 'Din ordre er bekræftet.',
        fi: 'Tilauksesi on vahvistettu.',
        zh_CN: '您的订单已确认。',
        zh_TW: '您的訂單已確認。',
    },

    footerMessage: {
        en_US: 'Is there anything else I can help you with?',
        en_GB: 'Is there anything else I can help you with?',
        en: 'Is there anything else I can help you with?',
        de: 'Gibt es noch etwas anderes, womit ich Ihnen helfen kann?',
        es: '¿Hay algo más en lo que pueda ayudarte?',
        fr: 'Y a-t-il autre chose pour laquelle je peux vous aider ?',
        it: "C'è qualcos'altro con cui posso aiutarti?",
        ja: '他にお手伝いできることはございますか？',
        ko: '제가 도와드릴 다른 것이 있나요?',
        nl: 'Is er nog iets anders waarmee ik je kan helpen?',
        no: 'Er det noe annet jeg kan hjelpe deg med?',
        pl: 'Czy jest coś jeszcze, w czym mogę pomóc?',
        pt_BR: 'Há mais alguma coisa com que posso ajudar?',
        sv: 'Finns det något annat jag kan hjälpa dig med?',
        da: 'Er der noget andet, jeg kan hjælpe med?',
        fi: 'Onko jotain muuta, jossa voin auttaa?',
        zh_CN: '还有其他我可以帮助您的吗？',
        zh_TW: '還有其他我可以為您服務的嗎？',
    },

    orderSummaryAssistiveText: {
        en_US: 'Order Summary',
        en_GB: 'Order Summary',
        en: 'Order Summary',
        de: 'Bestellübersicht',
        es: 'Resumen del pedido',
        fr: 'Récapitulatif de la commande',
        it: 'Riepilogo ordine',
        ja: '注文概要',
        ko: '주문 요약',
        nl: 'Bestellingsoverzicht',
        no: 'Bestillingsoversikt',
        pl: 'Podsumowanie zamówienia',
        pt_BR: 'Resumo do pedido',
        sv: 'Beställningsöversikt',
        da: 'Ordreoversigt',
        fi: 'Tilausyhteenveto',
        zh_CN: '订单摘要',
        zh_TW: '訂單摘要',
    },

    cartSummaryAssistiveText: {
        en_US: 'Cart Summary',
        en_GB: 'Cart Summary',
        en: 'Cart Summary',
        de: 'Warenkorbübersicht',
        es: 'Resumen del carrito',
        fr: 'Récapitulatif du panier',
        it: 'Riepilogo carrello',
        ja: 'カート概要',
        ko: '장바구니 요약',
        nl: 'Winkelwagenoverzicht',
        no: 'Handlekurvoppsummering',
        pl: 'Podsumowanie koszyka',
        pt_BR: 'Resumo do carrinho',
        sv: 'Varukorgssammanfattning',
        da: 'Kurvoversigt',
        fi: 'Ostoskorin yhteenveto',
        zh_CN: '购物车摘要',
        zh_TW: '購物車摘要',
    },

    toggleExpandAssistiveText: {
        en_US: 'Expand order details',
        en_GB: 'Expand order details',
        en: 'Expand order details',
        de: 'Bestelldetails erweitern',
        es: 'Ampliar detalles del pedido',
        fr: 'Développer les détails de la commande',
        it: "Espandi dettagli dell'ordine",
        ja: '注文の詳細を展開',
        ko: '주문 세부정보 펼치기',
        nl: 'Bestelgegevens uitklappen',
        no: 'Utvid bestillingsdetaljer',
        pl: 'Rozwiń szczegóły zamówienia',
        pt_BR: 'Expandir detalhes do pedido',
        sv: 'Expandera beställningsdetaljer',
        da: 'Udvid ordredetaljer',
        fi: 'Laajenna tilauksen tiedot',
        zh_CN: '展开订单详情',
        zh_TW: '展開訂單詳細資料',
    },

    toggleCollapseAssistiveText: {
        en_US: 'Collapse order details',
        en_GB: 'Collapse order details',
        en: 'Collapse order details',
        de: 'Bestelldetails einklappen',
        es: 'Contraer detalles del pedido',
        fr: 'Réduire les détails de la commande',
        it: "Comprimi dettagli dell'ordine",
        ja: '注文の詳細を折りたたむ',
        ko: '주문 세부정보 접기',
        nl: 'Bestelgegevens inklappen',
        no: 'Skjul bestillingsdetaljer',
        pl: 'Zwiń szczegóły zamówienia',
        pt_BR: 'Recolher detalhes do pedido',
        sv: 'Minimera beställningsdetaljer',
        da: 'Skjul ordredetaljer',
        fi: 'Tiivistä tilauksen tiedot',
        zh_CN: '收起订单详情',
        zh_TW: '收合訂單詳細資料',
    },

    toggleExpandCartAssistiveText: {
        en_US: 'Expand cart details',
        en_GB: 'Expand cart details',
        en: 'Expand cart details',
        de: 'Warenkorbdetails erweitern',
        es: 'Ampliar detalles del carrito',
        fr: 'Développer les détails du panier',
        it: 'Espandi dettagli del carrello',
        ja: 'カートの詳細を展開',
        ko: '장바구니 세부정보 펼치기',
        nl: 'Winkelwagengegevens uitklappen',
        no: 'Utvid handlekurvdetaljer',
        pl: 'Rozwiń szczegóły koszyka',
        pt_BR: 'Expandir detalhes do carrinho',
        sv: 'Expandera varukorgsdetaljer',
        da: 'Udvid kurvdetaljer',
        fi: 'Laajenna ostoskorin tiedot',
        zh_CN: '展开购物车详情',
        zh_TW: '展開購物車詳細資料',
    },

    toggleCollapseCartAssistiveText: {
        en_US: 'Collapse cart details',
        en_GB: 'Collapse cart details',
        en: 'Collapse cart details',
        de: 'Warenkorbdetails einklappen',
        es: 'Contraer detalles del carrito',
        fr: 'Réduire les détails du panier',
        it: 'Comprimi dettagli del carrello',
        ja: 'カートの詳細を折りたたむ',
        ko: '장바구니 세부정보 접기',
        nl: 'Winkelwagengegevens inklappen',
        no: 'Skjul handlekurvdetaljer',
        pl: 'Zwiń szczegóły koszyka',
        pt_BR: 'Recolher detalhes do carrinho',
        sv: 'Minimera varukorgsdetaljer',
        da: 'Skjul kurvdetaljer',
        fi: 'Tiivistä ostoskorin tiedot',
        zh_CN: '收起购物车详情',
        zh_TW: '收合購物車詳細資料',
    },

    orderItemsAssistiveText: {
        en_US: 'Order Items',
        en_GB: 'Order Items',
        en: 'Order Items',
        de: 'Bestellartikel',
        es: 'Artículos del pedido',
        fr: 'Articles de la commande',
        it: "Articoli dell'ordine",
        ja: '注文商品',
        ko: '주문 상품',
        nl: 'Bestelartikelen',
        no: 'Bestillingsvarer',
        pl: 'Pozycje zamówienia',
        pt_BR: 'Itens do pedido',
        sv: 'Beställningsartiklar',
        da: 'Ordrevarer',
        fi: 'Tilaustuotteet',
        zh_CN: '订单商品',
        zh_TW: '訂單商品',
    },

    cartItemsAssistiveText: {
        en_US: 'Cart Items',
        en_GB: 'Cart Items',
        en: 'Cart Items',
        de: 'Warenkorbartikel',
        es: 'Artículos del carrito',
        fr: 'Articles du panier',
        it: 'Articoli nel carrello',
        ja: 'カート内商品',
        ko: '장바구니 상품',
        nl: 'Winkelwagenartikelen',
        no: 'Handlekurvvarer',
        pl: 'Pozycje w koszyku',
        pt_BR: 'Itens do carrinho',
        sv: 'Varukorgsartiklar',
        da: 'Kurvvarer',
        fi: 'Ostoskorin tuotteet',
        zh_CN: '购物车商品',
        zh_TW: '購物車商品',
    },

    orderTotalsAssistiveText: {
        en_US: 'Order Total Breakdown',
        en_GB: 'Order Total Breakdown',
        en: 'Order Total Breakdown',
        de: 'Aufschlüsselung des Bestellbetrags',
        es: 'Desglose del total del pedido',
        fr: 'Détail du total de la commande',
        it: "Dettaglio totale dell'ordine",
        ja: '注文合計の内訳',
        ko: '주문 합계 내역',
        nl: 'Uitsplitsing van het bestelbedrag',
        no: 'Oversikt over bestillingstotal',
        pl: 'Zestawienie kwoty zamówienia',
        pt_BR: 'Detalhamento do total do pedido',
        sv: 'Uppdelning av beställningens total',
        da: 'Opgørelse over ordretotal',
        fi: 'Tilauksen kokonaissumman erittely',
        zh_CN: '订单总计明细',
        zh_TW: '訂單總計明細',
    },

    cartTotalsAssistiveText: {
        en_US: 'Cart Total Breakdown',
        en_GB: 'Cart Total Breakdown',
        en: 'Cart Total Breakdown',
        de: 'Aufschlüsselung des Warenkorbgesamtbetrags',
        es: 'Desglose del total del carrito',
        fr: 'Détail du total du panier',
        it: 'Dettaglio totale del carrello',
        ja: 'カート合計の内訳',
        ko: '장바구니 합계 내역',
        nl: 'Uitsplitsing van het winkelwagenbedrag',
        no: 'Oversikt over handlekurvtotal',
        pl: 'Zestawienie kwoty koszyka',
        pt_BR: 'Detalhamento do total do carrinho',
        sv: 'Uppdelning av varukorgens total',
        da: 'Opgørelse over kurvtotal',
        fi: 'Ostoskorin kokonaissumman erittely',
        zh_CN: '购物车总计明细',
        zh_TW: '購物車總計明細',
    },

    orderIdLabel: {
        en_US: 'Order ID',
        en_GB: 'Order ID',
        en: 'Order ID',
        de: 'Bestellnummer',
        es: 'ID del pedido',
        fr: 'ID de commande',
        it: 'ID ordine',
        ja: '注文ID',
        ko: '주문 ID',
        nl: 'Bestel-ID',
        no: 'Bestillings-ID',
        pl: 'ID zamówienia',
        pt_BR: 'ID do pedido',
        sv: 'Beställnings-ID',
        da: 'Ordre-id',
        fi: 'Tilaus-ID',
        zh_CN: '订单编号',
        zh_TW: '訂單編號',
    },
};
