import type { OrderItem } from 'commerce_my_account/orderDeliveryGroupContainer';
export const orderItems: OrderItem[] = [
    {
        fields: [
            {
                dataName: 'CurrencyIsoCode',
                label: 'Currency ISO Code',
                text: 'USD',
                type: 'picklist',
            },
            {
                dataName: 'TotalAdjustmentAmount',
                label: 'Adjustments',
                text: '-3.03',
                type: 'currency',
            },
            {
                dataName: 'TotalAdjustmentAmtWithTax',
                label: 'Adjustments with Tax',
                text: '-2.83',
                type: 'currency',
            },
            {
                dataName: 'CreatedDate',
                label: 'Created Date',
                text: '2022-09-28T11:16:15.000Z',
                type: 'datetime',
            },
            {
                dataName: 'Product2Id',
                label: 'Product ID',
                text: '01tOG000000G2fZYAS',
                type: 'reference',
            },
            {
                dataName: 'TotalAdjustmentDistAmount',
                label: 'Distributed Order Adjustments',
                text: '-0.97',
                type: 'currency',
            },
            {
                dataName: 'AdjustedLineAmount',
                label: 'Adjusted Line Subtotal',
                text: '18.44',
                type: 'currency',
            },
            {
                dataName: 'TotalAdjustedLineTaxAmount',
                label: 'Adjusted Line Subtotal Tax',
                text: '1.64',
                type: 'currency',
            },
            {
                dataName: 'TotalAdjustmentDistTaxAmount',
                label: 'Distributed Order Adjustments Tax',
                text: '0.2',
                type: 'currency',
            },
            {
                dataName: 'TotalAdjustmentTaxAmount',
                label: 'Adjustments Tax',
                text: '0.2',
                type: 'currency',
            },
            {
                dataName: 'OrderSummaryId',
                label: 'Order Summary ID',
                text: '1OsOG00000002f00AA',
                type: 'reference',
            },
            {
                dataName: 'Id',
                label: 'Order Product Summary ID',
                text: '10uOG00000002mfYAA',
                type: 'id',
            },
            {
                dataName: 'OrderDeliveryGroupSummaryId',
                label: 'Order Delivery Group Summary ID',
                text: '0agOG00000002f0YAA',
                type: 'reference',
            },
            {
                dataName: 'ListPrice',
                label: 'List Price',
                text: '24.99',
                type: 'currency',
            },
            {
                dataName: 'AdjustedLineAmtWithTax',
                label: 'Line Total',
                text: '20.08',
                type: 'currency',
            },
            {
                dataName: 'TotalPrice',
                label: 'Pretax Total',
                text: '17.47',
                type: 'currency',
            },
            {
                dataName: 'StockKeepingUnit',
                label: 'Product Sku',
                text: '6010009',
                type: 'string',
            },
            {
                dataName: 'Quantity',
                label: 'Quantity',
                text: '1.0',
                type: 'double',
            },
            {
                dataName: 'LineNumber',
                label: 'Order Line Number',
                text: '3',
                type: 'int',
            },
            {
                dataName: 'QuantityAvailableToReturn',
                label: 'Quantity Available to Return',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityFulfilled',
                label: 'Quantity Fulfilled',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityAvailableToFulfill',
                label: 'Quantity Available to Fulfill',
                text: '1.0',
                type: 'double',
            },
            {
                dataName: 'QuantityReturnInitiated',
                label: 'Quantity Return Initiated',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityAllocated',
                label: 'Quantity Allocated',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityNetOrdered',
                label: 'Quantity Net Ordered',
                text: '1.0',
                type: 'double',
            },
            {
                dataName: 'QuantityReturned',
                label: 'Quantity Returned',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityCanceled',
                label: 'Quantity Canceled',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityAvailableToCancel',
                label: 'Quantity Available to Cancel',
                text: '1.0',
                type: 'double',
            },
            {
                dataName: 'QuantityOrdered',
                label: 'Quantity Ordered',
                text: '1.0',
                type: 'double',
            },
            {
                dataName: 'Status',
                label: 'Status',
                text: 'ORDERED',
                type: 'picklist',
            },
            {
                dataName: 'TotalAmtWithTax',
                label: 'Total with Tax',
                text: '19.31',
                type: 'currency',
            },
            {
                dataName: 'TotalTaxAmount',
                label: 'Tax',
                text: '1.84',
                type: 'currency',
            },
            {
                dataName: 'Type',
                label: 'Type',
                text: 'Order Product',
                type: 'picklist',
            },
            {
                dataName: 'TypeCode',
                label: 'Type Code',
                text: 'Product',
                type: 'picklist',
            },
            {
                dataName: 'UnitPrice',
                label: 'Unit Price',
                text: '20.5',
                type: 'currency',
            },
            {
                dataName: 'TotalLineAdjustmentAmount',
                label: 'Line Adjustments',
                text: '-2.06',
                type: 'currency',
            },
            {
                dataName: 'TotalLineAdjustmentTaxAmount',
                label: 'Line Adjustments Tax',
                text: '0.0',
                type: 'currency',
            },
            {
                dataName: 'TotalLineAdjustmentAmtWithTax',
                label: 'Line Adjustments with Tax',
                text: '-2.06',
                type: 'currency',
            },
            { dataName: 'TotalLineAmount', label: 'Line Subtotal', text: '20.5', type: 'currency' },
            {
                dataName: 'TotalLineAmountWithTax',
                label: 'Line Subtotal with Tax',
                text: '22.14',
                type: 'currency',
            },
            {
                dataName: 'GrossUnitPrice',
                label: 'Gross Unit Price',
                text: '22.14',
                type: 'currency',
            },
            {
                dataName: 'TotalLineTaxAmount',
                label: 'Line Subtotal Tax',
                text: '1.64',
                type: 'currency',
            },
            {
                dataName: 'Description',
                label: 'Description',
                text: 'A signature Alpine health and fitness beverage. This post-workout beverage with Chai flavor is designed to help athletes maximize recovery and gains. 0.5L PET',
                type: 'TEXTAREA',
            },
            {
                dataName: 'TotalAdjustmentDistAmtWithTax',
                label: 'Distributed Order Adjustments with Tax',
                text: '-0.77',
                type: 'currency',
            },
            {
                dataName: 'LastModifiedDate',
                label: 'Last Modified Date',
                text: '2022-11-14T10:45:47.000Z',
                type: 'datetime',
            },
            {
                dataName: 'EndDate',
                label: 'End Date',
                text: '2022-11-14T10:45:47.000Z',
                type: 'datetime',
            },
            {
                dataName: 'Name',
                label: 'Name',
                text: 'Alpine Energy Drink Chai Post 0.5L PET - 6 pack',
                type: 'string',
            },
            { dataName: 'Family', label: 'Product Family', text: 'Apline Nutrition', type: 'string' },
            { dataName: 'QuantityUnitOfMeasure', label: 'Quantity Unit Of Measure', text: 'Each', type: 'string' },
            { dataName: 'ProductCode', label: 'Product Code', text: 'NUTRITIONPRODUCT', type: 'string' },
            {
                dataName: 'TotalLinePromotionAmount',
                label: 'Line Item Promotions Applied',
                text: '-2.06',
                type: 'currency',
            },
            {
                dataName: 'TotalPromotionDistAmount',
                label: 'Order Level Promotions Applied',
                text: '-0.97',
                type: 'currency',
            },
        ],
        orderItemSummaryId: '10uOG00000002mfYAA',
        media: {
            alternateText: null,
            contentVersionId: null,
            id: '2pmOG00000000d0YAA',
            mediaType: null,
            sortOrder: 0,
            thumbnailUrl: null,
            title: 'northerntrailoutfitterscom-nto-alpine-nutrition-default-images-large-6pack-chai-post-largejpg',
            url: 'https://s3.amazonaws.com/northerntrailoutfitters.com/nto-alpine-nutrition/default/images/large/6Pack-Chai-Post-Large.jpg',
        },
        isValid: true,
        productId: '01tOG000000G2fZYAS',
        name: 'Alpine Energy Drink Chai Post 0.5L PET - 6 pack',
        adjustments: [
            {
                currencyIsoCode: 'USD',
                type: 'Promotion',
                name: '5% OFF Chai And Protein Products',
                id: 0,
                discountAmount: '-1.03',
            },
            {
                currencyIsoCode: 'USD',
                type: 'Promotion',
                name: 'DRINKS5OFF - 5% OFF Coupon For Protein Product',
                id: 1,
                discountAmount: '-1.03',
            },
        ],
        variants: [
            {
                name: 'Size',
                value: '0.5L',
            },
            {
                name: 'Category',
                value: 'Nutrition',
            },
        ],
    },
    {
        fields: [
            {
                dataName: 'CurrencyIsoCode',
                label: 'Currency ISO Code',
                text: 'USD',
                type: 'picklist',
            },
            {
                dataName: 'TotalAdjustmentAmount',
                label: 'Adjustments',
                text: '-3.57',
                type: 'currency',
            },
            {
                dataName: 'TotalAdjustmentAmtWithTax',
                label: 'Adjustments with Tax',
                text: '-2.97',
                type: 'currency',
            },
            {
                dataName: 'CreatedDate',
                label: 'Created Date',
                text: '2022-09-28T11:16:15.000Z',
                type: 'datetime',
            },
            {
                dataName: 'Product2Id',
                label: 'Product ID',
                text: '01tOG000000G2fqYAC',
                type: 'reference',
            },
            {
                dataName: 'TotalAdjustmentDistAmount',
                label: 'Distributed Order Adjustments',
                text: '-1.74',
                type: 'currency',
            },
            {
                dataName: 'AdjustedLineAmount',
                label: 'Adjusted Line Subtotal',
                text: '34.67',
                type: 'currency',
            },
            {
                dataName: 'TotalAdjustedLineTaxAmount',
                label: 'Adjusted Line Subtotal Tax',
                text: '3.22',
                type: 'currency',
            },
            {
                dataName: 'TotalAdjustmentDistTaxAmount',
                label: 'Distributed Order Adjustments Tax',
                text: '0.3',
                type: 'currency',
            },
            {
                dataName: 'TotalAdjustmentTaxAmount',
                label: 'Adjustments Tax',
                text: '0.6',
                type: 'currency',
            },
            {
                dataName: 'OrderSummaryId',
                label: 'Order Summary ID',
                text: '1OsOG00000002f00AA',
                type: 'reference',
            },
            {
                dataName: 'Id',
                label: 'Order Product Summary ID',
                text: '10uOG00000002mhYAA',
                type: 'id',
            },
            {
                dataName: 'OrderDeliveryGroupSummaryId',
                label: 'Order Delivery Group Summary ID',
                text: '0agOG00000002f0YAA',
                type: 'reference',
            },
            {
                dataName: 'ListPrice',
                label: 'List Price',
                text: '37.5',
                type: 'currency',
            },
            {
                dataName: 'AdjustedLineAmtWithTax',
                label: 'Line Total',
                text: '37.89',
                type: 'currency',
            },
            {
                dataName: 'TotalPrice',
                label: 'Pretax Total',
                text: '32.93',
                type: 'currency',
            },
            {
                dataName: 'StockKeepingUnit',
                label: 'Product Sku',
                text: '6010003124',
                type: 'string',
            },
            {
                dataName: 'Quantity',
                label: 'Quantity',
                text: '1.0',
                type: 'double',
            },
            {
                dataName: 'LineNumber',
                label: 'Order Line Number',
                text: '1',
                type: 'int',
            },
            {
                dataName: 'QuantityAvailableToReturn',
                label: 'Quantity Available to Return',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityFulfilled',
                label: 'Quantity Fulfilled',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityAvailableToFulfill',
                label: 'Quantity Available to Fulfill',
                text: '1.0',
                type: 'double',
            },
            {
                dataName: 'QuantityReturnInitiated',
                label: 'Quantity Return Initiated',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityAllocated',
                label: 'Quantity Allocated',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityNetOrdered',
                label: 'Quantity Net Ordered',
                text: '1.0',
                type: 'double',
            },
            {
                dataName: 'QuantityReturned',
                label: 'Quantity Returned',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityCanceled',
                label: 'Quantity Canceled',
                text: '0.0',
                type: 'double',
            },
            {
                dataName: 'QuantityAvailableToCancel',
                label: 'Quantity Available to Cancel',
                text: '1.0',
                type: 'double',
            },
            {
                dataName: 'QuantityOrdered',
                label: 'Quantity Ordered',
                text: '1.0',
                type: 'double',
            },
            {
                dataName: 'Status',
                label: 'Status',
                text: 'ORDERED',
                type: 'picklist',
            },
            {
                dataName: 'TotalAmtWithTax',
                label: 'Total with Tax',
                text: '36.45',
                type: 'currency',
            },
            {
                dataName: 'TotalTaxAmount',
                label: 'Tax',
                text: '3.52',
                type: 'currency',
            },
            {
                dataName: 'Type',
                label: 'Type',
                text: 'Order Product',
                type: 'picklist',
            },
            {
                dataName: 'TypeCode',
                label: 'Type Code',
                text: 'Product',
                type: 'picklist',
            },
            {
                dataName: 'UnitPrice',
                label: 'Unit Price',
                text: '36.5',
                type: 'currency',
            },
            {
                dataName: 'TotalLineAdjustmentAmount',
                label: 'Line Adjustments',
                text: '-1.83',
                type: 'currency',
            },
            {
                dataName: 'TotalLineAdjustmentAmtWithTax',
                label: 'Line Adjustments with Tax',
                text: '-1.53',
                type: 'currency',
            },
            {
                dataName: 'TotalLineAdjustmentTaxAmount',
                label: 'Line Adjustments Tax',
                text: '0.3',
                type: 'currency',
            },
            { dataName: 'TotalLineAmount', label: 'Line Subtotal', text: '36.5', type: 'currency' },
            {
                dataName: 'TotalLineAmountWithTax',
                label: 'Line Subtotal with Tax',
                text: '39.42',
                type: 'currency',
            },
            {
                dataName: 'GrossUnitPrice',
                label: 'Gross Unit Price',
                text: '39.42',
                type: 'currency',
            },
            {
                dataName: 'TotalLineTaxAmount',
                label: 'Line Subtotal Tax',
                text: '2.92',
                type: 'currency',
            },
            {
                dataName: 'Description',
                label: 'Description',
                text: 'Hi-Protein GoBars are an athletes favorite with it unique taste and healthy composition.',
                type: 'TEXTAREA',
            },

            {
                dataName: 'TotalAdjustmentDistAmtWithTax',
                label: 'Distributed Order Adjustments with Tax',
                text: '-1.44',
                type: 'currency',
            },

            {
                dataName: 'LastModifiedDate',
                label: 'Last Modified Date',
                text: '2022-11-14T10:44:47.000Z',
                type: 'datetime',
            },
            {
                dataName: 'EndDate',
                label: 'End Date',
                text: '2022-11-14T10:45:47.000Z',
                type: 'datetime',
            },
            {
                dataName: 'Name',
                label: 'Name',
                text: 'GoBar Tart Cherry Hi Protein, 2oz 24 Pack (Case)',
                type: 'string',
            },
            { dataName: 'Family', label: 'Product Family', text: 'Apline Energy', type: 'string' },
            { dataName: 'QuantityUnitOfMeasure', label: 'Quantity Unit Of Measure', text: 'Each', type: 'string' },
            { dataName: 'ProductCode', label: 'Product Code', text: 'ENERGYPRODUCT', type: 'string' },
            {
                dataName: 'TotalLinePromotionAmount',
                label: 'Line Item Promotions Applied',
                text: '-1.83',
                type: 'currency',
            },
            {
                dataName: 'TotalPromotionDistAmount',
                label: 'Order Level Promotions Applied',
                text: '-1.74',
                type: 'currency',
            },
        ],
        orderItemSummaryId: '10uOG00000002mhYAA',
        media: {
            alternateText: null,
            contentVersionId: null,
            id: '2pmOG00000000chYAA',
            mediaType: null,
            sortOrder: 0,
            thumbnailUrl: null,
            title: 'northerntrailoutfitterscom-nto-alpine-nutrition-default-images-large-barsboxof12gocherrylargepng',
            url: 'https://s3.amazonaws.com/northerntrailoutfitters.com/nto-alpine-nutrition/default/images/large/BarsBoxof12_Go_Cherry_Large.png',
        },
        isValid: true,
        productId: '01tOG000000G2fqYAC',
        name: 'GoBar Tart Cherry Hi Protein, 2oz 24 Pack (Case)',
        adjustments: [
            {
                currencyIsoCode: 'USD',
                type: 'Promotion',
                name: '5% OFF Chai And Protein Products',
                id: 0,
                discountAmount: '-1.83',
            },
        ],
        variants: [
            {
                name: 'Size',
                value: '2oz',
            },
            {
                name: 'Category',
                value: 'Energy',
            },
        ],
    },
];

export const shippingFieldsData = [
    {
        dataName: 'Id',

        label: 'Order Delivery Method ID',
        text: '2DmOG00000001IZ0AY',
        type: 'id',
    },
    {
        dataName: 'GrandTotalAmount',

        label: 'Total with Tax',
        text: '10.55',
        type: 'currency',
    },
    {
        dataName: 'Id',

        label: 'Order Delivery Group Summary ID',
        text: '0agOG00000002f0YAA',
        type: 'id',
    },
    {
        dataName: 'OrderDeliveryMethodId',

        label: 'Order Delivery Method ID',
        text: '2DmOG00000001IZ0AY',
        type: 'reference',
    },
    {
        dataName: 'Name',

        label: 'Name',
        text: 'USPS',
        type: 'string',
    },
    {
        dataName: 'DeliverToAddress',
        dataType: 'urn:address',
        label: 'Shipping Address',
        text: 'API address [ 121 Spear St, San Francisco, CA, 94105, US, null, null, null, null, null]',
        type: 'address',
    },
    {
        dataName: 'CurrencyIsoCode',

        label: 'Currency ISO Code',
        text: 'USD',
        type: 'picklist',
    },
    {
        dataName: 'TotalLineAmount',

        label: 'Subtotal',
        text: '11.99',
        type: 'currency',
    },
    {
        dataName: 'TotalTaxAmount',

        label: 'Tax',
        text: '1.56',
        type: 'currency',
    },
    {
        dataName: 'TotalLineAmtWithTax',

        label: 'Subtotal with Tax',
        text: '12.95',
        type: 'currency',
    },
    {
        dataName: 'TotalLineTaxAmount',

        label: 'Subtotal Tax',
        text: '0.96',
        type: 'currency',
    },
    {
        dataName: 'TotalAmount',

        label: 'Pretax Total',
        text: '8.99',
        type: 'currency',
    },
    {
        dataName: 'IsGift',
        dataType: 'xsd:boolean',
        label: 'Is Gift',
        text: 'false',
        type: 'boolean',
    },
    {
        dataName: 'ClassOfService',

        label: 'Class of Service',
        text: 'SNC9600',
        type: 'picklist',
    },
    {
        dataName: 'DesiredDeliveryDate',

        label: 'Desired Delivery Date',
        text: '2022-10-28T00:00:00.000Z',
        type: 'datetime',
    },
    {
        dataName: 'Carrier',

        label: 'Carrier',
        text: 'Test Carrier',
        type: 'picklist',
    },
    {
        dataName: 'TotalAdjustmentAmtWithTax',

        label: 'Adjustments with Tax',
        text: '-2.4',
        type: 'currency',
    },
    {
        dataName: 'TotalAdjustmentAmount',

        label: 'Adjustments',
        text: '-3.0',
        type: 'currency',
    },
    {
        dataName: 'TotalAdjustmentTaxAmount',

        label: 'Adjustments Tax',
        text: '0.6',
        type: 'currency',
    },
    {
        dataName: 'ClassOfService',

        label: 'Class of Service',
        text: 'SNC9600',
        type: 'picklist',
    },
    { dataName: 'Description', label: 'Description', text: 'Fast delivery method', type: 'textarea' },
    {
        dataName: 'DeliveryInstructions',
        label: 'Delivery Instructions',
        type: 'Long Text Area(2000)',
        text: 'Please drop off the package at the front door.',
    },
    {
        dataName: 'GiftMessage',
        label: 'Gift Message',
        type: 'Long Text Area(2000)',
        text: 'A suprise gift for a warm friend.',
    },
    { dataName: 'EmailAddress', label: 'Email Address', text: 'hgranger@dumbledore.edu', type: 'email' },
    {
        dataName: 'PromisedDeliveryDate',
        label: 'Promised Delivery Date',
        text: '2022-12-05T00:51:27.000Z',
        type: 'datetime',
    },
    { dataName: 'PhoneNumber', label: 'Phone Number', type: 'Phone', text: '403-123-4567' },
    { dataName: 'ReferenceNumber', label: 'Reference Number', type: 'Text(255)', text: '1111111' },
];

export const defaultItemFields = [
    [
        {
            dataName: 'StockKeepingUnit',
            label: 'Product Sku',
            text: '6010039',
            type: 'string',
        },
        {
            dataName: 'Quantity',
            label: 'Quantity',
            text: '1.0',
            type: 'double',
        },
        {
            dataName: 'AdjustedLineAmount',
            label: 'Adjusted Line Subtotal',
            text: '18.44',
            type: 'currency',
        },
        {
            dataName: 'TotalLineAdjustmentAmount',
            label: 'Line Adjustments',
            text: '-2.06',
            type: 'currency',
        },
    ],
    [
        {
            dataName: 'StockKeepingUnit',
            label: 'Product Sku',
            text: '6728336',
            type: 'string',
        },
        {
            dataName: 'Quantity',
            label: 'Quantity',
            text: '1.0',
            type: 'double',
        },
        {
            dataName: 'AdjustedLineAmount',
            label: 'Adjusted Line Subtotal',
            text: '34.67',
            type: 'currency',
        },
        {
            dataName: 'TotalLineAdjustmentAmount',
            label: 'Line Adjustments',
            text: '-1.83',
            type: 'currency',
        },
    ],
];

export const defaultShippingFields = [
    {
        dataName: 'Name',
        label: 'Name',
        text: 'USPS',
        type: 'string',
    },
    {
        dataName: 'TotalLineAmount',
        label: 'Subtotal',
        text: '11.99',
        type: 'currency',
    },
];
