/*
 * Copyright (c) 2023, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * For full license text, see the LICENSE file in the repo
 * root or https://opensource.org/licenses/apache-2.0/
 */

/*
 * @description Label data with multi-locale support for productDetails
 */

// Label data with multi-locale support
export const LABEL_DATA = {
    // Product Pricing Labels
    Product_Pricing_strikethroughAssistiveText: {
        en_US: 'Crossed Out',
        en_GB: 'Crossed out',
        en: 'Crossed out',
        de: 'Durchgestrichen',
        es: 'Tachado',
        fr: 'Barré',
        it: 'Barrato',
        ja: '取り消し線',
        ko: '취소선',
        nl: 'Doorgestreept',
        no: 'Gjennomstreket',
        pl: 'Przekreślone',
        pt_BR: 'Riscado',
        sv: 'Genomstruken',
        da: 'Gennemstreget',
        fi: 'Yliviivattu',
        zh_CN: '删除线',
        zh_TW: '刪除線',
    },

    Product_addToCartAssistiveText: {
        en_US: 'Add To Cart',
        en_GB: 'Add to basket',
        en: 'Add To Cart',
        de: 'In den Warenkorb',
        es: 'Agregar al carrito',
        fr: 'Ajouter au panier',
        it: 'Aggiungi al carrello',
        ja: 'カートに追加',
        ko: '장바구니에 추가',
        nl: 'Toevoegen aan winkelwagen',
        no: 'Legg i handlekurv',
        pl: 'Dodaj do koszyka',
        pt_BR: 'Adicionar ao carrinho',
        sv: 'Lägg i varukorg',
        da: 'Tilføj til kurv',
        fi: 'Lisää ostoskoriin',
        zh_CN: '加入购物车',
        zh_TW: '加入購物車',
    },

    Product_quantityLabelAssistiveText: {
        en_US: 'Quantity',
        en_GB: 'Quantity',
        en: 'Quantity',
        de: 'Menge',
        es: 'Cantidad',
        fr: 'Quantité',
        it: 'Quantità',
        ja: '数量',
        ko: '수량',
        nl: 'Aantal',
        no: 'Antall',
        pl: 'Ilość',
        pt_BR: 'Quantidade',
        sv: 'Antal',
        da: 'Antal',
        fi: 'Määrä',
        zh_CN: '数量',
        zh_TW: '數量',
    },

    Product_quantityLabelText: {
        en_US: 'Qty',
        en_GB: 'Qty',
        en: 'Qty',
        de: 'Menge',
        es: 'Cant.',
        fr: 'Qté',
        it: 'Q.tà',
        ja: '数量',
        ko: '수량',
        nl: 'Aantal',
        no: 'Antall',
        pl: 'Ilość',
        pt_BR: 'Qtd',
        sv: 'Antal',
        da: 'Antal',
        fi: 'Määrä',
        zh_CN: '数量',
        zh_TW: '數量',
    },

    Product_originalPriceLabelText: {
        en_US: 'Original price',
        en_GB: 'Original price',
        en: 'Original price',
        de: 'Ursprünglicher Preis',
        es: 'Precio original',
        fr: "Prix d'origine",
        it: 'Prezzo originale',
        ja: '元の価格',
        ko: '원래 가격',
        nl: 'Oorspronkelijke prijs',
        no: 'Opprinnelig pris',
        pl: 'Cena pierwotna',
        pt_BR: 'Preço original',
        sv: 'Ordinarie pris',
        da: 'Oprindelig pris',
        fi: 'Alkuperäinen hinta',
        zh_CN: '原价',
        zh_TW: '原價',
    },

    Product_currentPriceLabelText: {
        en_US: 'Current price',
        en_GB: 'Current price',
        en: 'Current price',
        de: 'Aktueller Preis',
        es: 'Precio actual',
        fr: 'Prix actuel',
        it: 'Prezzo attuale',
        ja: '現在の価格',
        ko: '현재 가격',
        nl: 'Huidige prijs',
        no: 'Nåværende pris',
        pl: 'Aktualna cena',
        pt_BR: 'Preço atual',
        sv: 'Nuvarande pris',
        da: 'Nuværende pris',
        fi: 'Nykyinen hinta',
        zh_CN: '现价',
        zh_TW: '現價',
    },

    Product_currentPriceAssistiveText: {
        en_US: 'Current price',
        en_GB: 'Current price',
        en: 'Current price',
        de: 'Aktueller Preis',
        es: 'Precio actual',
        fr: 'Prix actuel',
        it: 'Prezzo attuale',
        ja: '現在の価格',
        ko: '현재 가격',
        nl: 'Huidige prijs',
        no: 'Nåværende pris',
        pl: 'Aktualna cena',
        pt_BR: 'Preço atual',
        sv: 'Nuvarande pris',
        da: 'Nuværende pris',
        fi: 'Nykyinen hinta',
        zh_CN: '现价',
        zh_TW: '現價',
    },

    Product_originalPriceAssistiveText: {
        en_US: 'Original price strikethrough',
        en_GB: 'Original price strikethrough',
        en: 'Original price strikethrough',
        de: 'Ursprünglicher Preis durchgestrichen',
        es: 'Precio original tachado',
        fr: "Prix d'origine barré",
        it: 'Prezzo originale barrato',
        ja: '元の価格（取り消し線）',
        ko: '원래 가격 취소선',
        nl: 'Oorspronkelijke prijs doorgestreept',
        no: 'Opprinnelig pris gjennomstreket',
        pl: 'Cena pierwotna przekreślona',
        pt_BR: 'Preço original riscado',
        sv: 'Ordinarie pris överstruken',
        da: 'Oprindelig pris gennemstreget',
        fi: 'Alkuperäinen hinta yliviivattu',
        zh_CN: '原价删除线',
        zh_TW: '原價刪除線',
    },

    Product_pricingSectionAssistiveText: {
        en_US: 'Product Pricing',
        en_GB: 'Product Pricing',
        en: 'Product Pricing',
        de: 'Produktpreise',
        es: 'Precios del producto',
        fr: 'Tarification du produit',
        it: 'Prezzi del prodotto',
        ja: '商品の価格',
        ko: '상품 가격',
        nl: 'Productprijzen',
        no: 'Produktpriser',
        pl: 'Ceny produktu',
        pt_BR: 'Preços do produto',
        sv: 'Produktpriser',
        da: 'Produktpriser',
        fi: 'Tuotteen hinnat',
        zh_CN: '产品价格',
        zh_TW: '產品價格',
    },

    Product_featuresSectionAssistiveText: {
        en_US: 'Product Features',
        en_GB: 'Product Features',
        en: 'Product Features',
        de: 'Produkteigenschaften',
        es: 'Características del producto',
        fr: 'Caractéristiques du produit',
        it: 'Caratteristiche del prodotto',
        ja: '商品の特徴',
        ko: '제품 특징',
        nl: 'Productkenmerken',
        no: 'Produktfunksjoner',
        pl: 'Cechy produktu',
        pt_BR: 'Características do produto',
        sv: 'Produktfunktioner',
        da: 'Produktegenskaber',
        fi: 'Tuotteen ominaisuudet',
        zh_CN: '产品特点',
        zh_TW: '產品特點',
    },

    Product_variantsSectionAssistiveText: {
        en_US: 'Product Variants',
        en_GB: 'Product Variants',
        en: 'Product Variants',
        de: 'Produktvarianten',
        es: 'Variantes del producto',
        fr: 'Variantes du produit',
        it: 'Varianti del prodotto',
        ja: '商品のバリエーション',
        ko: '제품 종류',
        nl: 'Productvarianten',
        no: 'Produktvarianter',
        pl: 'Warianty produktu',
        pt_BR: 'Variantes do produto',
        sv: 'Produktvarianter',
        da: 'Produktvarianter',
        fi: 'Tuotevariaatiot',
        zh_CN: '产品型号',
        zh_TW: '產品變體',
    },

    Product_quantitySectionAssistiveText: {
        en_US: 'Quantity Selection',
        en_GB: 'Quantity Selection',
        en: 'Quantity Selection',
        de: 'Mengenauswahl',
        es: 'Selección de cantidad',
        fr: 'Sélection de la quantité',
        it: 'Selezione quantità',
        ja: '数量の選択',
        ko: '수량 선택',
        nl: 'Aantal selectie',
        no: 'Antallsvalg',
        pl: 'Wybór ilości',
        pt_BR: 'Seleção de quantidade',
        sv: 'Antalsval',
        da: 'Antalsvalg',
        fi: 'Määrän valinta',
        zh_CN: '数量选择',
        zh_TW: '數量選擇',
    },

    Product_quantityControlsAssistiveText: {
        en_US: 'Quantity Controls',
        en_GB: 'Quantity Controls',
        en: 'Quantity Controls',
        de: 'Mengenkontrollen',
        es: 'Controles de cantidad',
        fr: 'Contrôles de quantité',
        it: 'Controlli quantità',
        ja: '数量コントロール',
        ko: '수량 컨트롤',
        nl: 'Aantal besturingselementen',
        no: 'Antallskontroller',
        pl: 'Kontrola ilości',
        pt_BR: 'Controles de quantidade',
        sv: 'Antalskontroller',
        da: 'Antalskontroller',
        fi: 'Määrän ohjaimet',
        zh_CN: '数量控制',
        zh_TW: '數量控制',
    },

    Product_decreaseQuantityAssistiveText: {
        en_US: 'Decrease quantity',
        en_GB: 'Decrease quantity',
        en: 'Decrease quantity',
        de: 'Menge verringern',
        es: 'Disminuir cantidad',
        fr: 'Diminuer la quantité',
        it: 'Diminuisci quantità',
        ja: '数量を減らす',
        ko: '수량 감소',
        nl: 'Aantal verminderen',
        no: 'Reduser mengde',
        pl: 'Zmniejsz ilość',
        pt_BR: 'Diminuir quantidade',
        sv: 'Minska antal',
        da: 'Reducer antal',
        fi: 'Vähennä määrää',
        zh_CN: '减少数量',
        zh_TW: '減少數量',
    },

    Product_increaseQuantityAssistiveText: {
        en_US: 'Increase quantity',
        en_GB: 'Increase quantity',
        en: 'Increase quantity',
        de: 'Menge erhöhen',
        es: 'Aumentar cantidad',
        fr: 'Augmenter la quantité',
        it: 'Aumenta quantità',
        ja: '数量を増やす',
        ko: '수량 증가',
        nl: 'Aantal verhogen',
        no: 'Øk mengde',
        pl: 'Zwiększ ilość',
        pt_BR: 'Aumentar quantidade',
        sv: 'Öka antal',
        da: 'Forøg antal',
        fi: 'Lisää määrää',
        zh_CN: '增加数量',
        zh_TW: '增加數量',
    },

    Product_loadingSpinnerAltText: {
        en_US: 'Loading express payment options...',
        en_GB: 'Loading express payment options...',
        en: 'Loading express payment options...',
        de: 'Express-Zahlungsoptionen werden geladen...',
        es: 'Cargando opciones de pago exprés...',
        fr: 'Chargement des options de paiement express…',
        it: 'Caricamento delle opzioni di pagamento rapido...',
        ja: 'エクスプレス決済オプションを読み込み中...',
        ko: '빠른 결제 옵션 불러오는 중...',
        nl: 'Snelle betaalopties laden...',
        no: 'Laster ekspressbetalingsalternativer...',
        pl: 'Ładowanie opcji szybkiej płatności...',
        pt_BR: 'Carregando opções de pagamento expresso...',
        sv: 'Läser in expressbetalningsalternativ...',
        da: 'Indlæser hurtige betalingsmuligheder...',
        fi: 'Ladataan pikamaksuvaihtoehtoja...',
        zh_CN: '正在加载快速支付选项...',
        zh_TW: '正在載入快速付款選項...',
    },
};
