/*
 * Copyright (c) 2025, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * For full license text, see the LICENSE file in the repo
 * root or https://opensource.org/licenses/apache-2.0/
 */

/*
 * @description Label data with multi-locale support for commonCarousel
 */

// Label data with multi-locale support
export const LABEL_DATA = {
    previousImage: {
        en_US: 'Previous image',
        en_GB: 'Previous image',
        en: 'Previous image',
        de: 'Vorheriges Bild',
        es: 'Imagen anterior',
        fr: 'Image précédente',
        it: 'Immagine precedente',
        ja: '前の画像',
        ko: '이전 이미지',
        nl: 'Vorige afbeelding',
        no: 'Forrige bilde',
        pl: 'Poprzednie zdjęcie',
        pt_BR: 'Imagem anterior',
        sv: 'Föregående bild',
        da: 'Forrige billede',
        fi: 'Edellinen kuva',
        zh_CN: '上一张图片',
        zh_TW: '上一張圖片',
    },

    nextImage: {
        en_US: 'Next image',
        en_GB: 'Next image',
        en: 'Next image',
        de: 'Nächstes Bild',
        es: 'Siguiente imagen',
        fr: 'Image suivante',
        it: 'Immagine successiva',
        ja: '次の画像',
        ko: '다음 이미지',
        nl: 'Volgende afbeelding',
        no: 'Neste bilde',
        pl: 'Następne zdjęcie',
        pt_BR: 'Próxima imagem',
        sv: 'Nästa bild',
        da: 'Næste billede',
        fi: 'Seuraava kuva',
        zh_CN: '下一张图片',
        zh_TW: '下一張圖片',
    },

    previousProduct: {
        en_US: 'Previous product',
        en_GB: 'Previous product',
        en: 'Previous product',
        de: 'Vorheriges Produkt',
        es: 'Producto anterior',
        fr: 'Produit précédent',
        it: 'Prodotto precedente',
        ja: '前の商品',
        ko: '이전 상품',
        nl: 'Vorig product',
        no: 'Forrige produkt',
        pl: 'Poprzedni produkt',
        pt_BR: 'Produto anterior',
        sv: 'Föregående produkt',
        da: 'Forrige produkt',
        fi: 'Edellinen tuote',
        zh_CN: '上一个商品',
        zh_TW: '上一個商品',
    },

    nextProduct: {
        en_US: 'Next product',
        en_GB: 'Next product',
        en: 'Next product',
        de: 'Nächstes Produkt',
        es: 'Siguiente producto',
        fr: 'Produit suivant',
        it: 'Prodotto successivo',
        ja: '次の商品',
        ko: '다음 상품',
        nl: 'Volgend product',
        no: 'Neste produkt',
        pl: 'Następny produkt',
        pt_BR: 'Próximo produto',
        sv: 'Nästa produkt',
        da: 'Næste produkt',
        fi: 'Seuraava tuote',
        zh_CN: '下一个商品',
        zh_TW: '下一個商品',
    },

    productPrice: {
        en_US: 'Product Price',
        en_GB: 'Product Price',
        en: 'Product Price',
        de: 'Produktpreis',
        es: 'Precio del producto',
        fr: 'Prix du produit',
        it: 'Prezzo del prodotto',
        ja: '商品価格',
        ko: '상품 가격',
        nl: 'Productprijs',
        no: 'Produktpris',
        pl: 'Cena produktu',
        pt_BR: 'Preço do produto',
        sv: 'Produktpris',
        da: 'Produktpris',
        fi: 'Tuotteen hinta',
        zh_CN: '商品价格',
        zh_TW: '商品價格',
    },

    viewImageAriaLabel: {
        en_US: 'View image {0} of {1}',
        en_GB: 'View image {0} of {1}',
        en: 'View image {0} of {1}',
        de: 'Bild {0} von {1} anzeigen',
        es: 'Ver imagen {0} de {1}',
        fr: "Voir l'image {0} de {1}",
        it: 'Vedi immagine {0} di {1}',
        ja: '画像 {0}/{1} を表示',
        ko: '이미지 {0}/{1} 보기',
        nl: 'Afbeelding {0} van {1} bekijken',
        no: 'Vis bilde {0} av {1}',
        pl: 'Wyświetl zdjęcie {0} z {1}',
        pt_BR: 'Ver imagem {0} de {1}',
        sv: 'Visa bild {0} av {1}',
        da: 'Vis billede {0} af {1}',
        fi: 'Näytä kuva {0}/{1}',
        zh_CN: '查看图片 {0}/{1}',
        zh_TW: '查看圖片 {0}/{1}',
    },

    viewProductAriaLabel: {
        en_US: 'View product {0} of {1}',
        en_GB: 'View product {0} of {1}',
        en: 'View product {0} of {1}',
        de: 'Produkt {0} von {1} anzeigen',
        es: 'Ver producto {0} de {1}',
        fr: 'Voir le produit {0} de {1}',
        it: 'Vedi prodotto {0} di {1}',
        ja: '商品 {0}/{1} を表示',
        ko: '상품 {0}/{1} 보기',
        nl: 'Product {0} van {1} bekijken',
        no: 'Vis produkt {0} av {1}',
        pl: 'Wyświetl produkt {0} z {1}',
        pt_BR: 'Ver produto {0} de {1}',
        sv: 'Visa produkt {0} av {1}',
        da: 'Vis produkt {0} af {1}',
        fi: 'Näytä tuote {0}/{1}',
        zh_CN: '查看商品 {0}/{1}',
        zh_TW: '查看商品 {0}/{1}',
    },

    outOfStock: {
        en_US: 'Out of Stock',
        en_GB: 'Out of Stock',
        en: 'Out of Stock',
        de: 'Nicht auf Lager',
        es: 'Sin stock',
        fr: 'En rupture de stock',
        it: 'Esaurito',
        ja: '在庫切れ',
        ko: '재고 없음',
        nl: 'Niet op voorraad',
        no: 'Ikke på lager',
        pl: 'Brak w magazynie',
        pt_BR: 'Fora de estoque',
        sv: 'Slut i lager',
        da: 'Ikke på lager',
        fi: 'Ei varastossa',
        zh_CN: '缺货',
        zh_TW: '缺貨',
    },
};
