/*
 * Copyright (c) 2025, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * For full license text, see the LICENSE file in the repo
 * root or https://opensource.org/licenses/apache-2-0/
 */
export const LABEL_DATA = {
    couponPlaceholder: {
        en_US: 'Enter coupon code...',
        en_GB: 'Enter coupon code...',
        en: 'Enter coupon code...',
        de: 'Gutscheincode eingeben...',
        es: 'Ingresa el código del cupón...',
        fr: 'Entrez le code promo...',
        it: 'Inserisci il codice coupon...',
        ja: 'クーポンコードを入力...',
        ko: '쿠폰 코드 입력...',
        nl: 'Voer couponcode in...',
        no: 'Skriv inn kupongkode...',
        pl: 'Wprowadź kod kuponu...',
        pt_BR: 'Digite o código do cupom...',
        sv: 'Ange kupongkod...',
        da: 'Indtast kuponkode...',
        fi: 'Anna kuponkikoodi...',
        zh_CN: '输入优惠券代码...',
        zh_TW: '輸入優惠券代碼...',
    },

    applyButtonLabel: {
        en_US: 'Apply',
        en_GB: 'Apply',
        en: 'Apply',
        de: 'Anwenden',
        es: 'Aplicar',
        fr: 'Appliquer',
        it: 'Applica',
        ja: '適用',
        ko: '적용',
        nl: 'Toepassen',
        no: 'Bruk',
        pl: 'Zastosuj',
        pt_BR: 'Aplicar',
        sv: 'Tillämpa',
        da: 'Anvend',
        fi: 'Käytä',
        zh_CN: '应用',
        zh_TW: '套用',
    },

    applyButtonAriaLabel: {
        en_US: 'Apply coupon code',
        en_GB: 'Apply coupon code',
        en: 'Apply coupon code',
        de: 'Gutscheincode anwenden',
        es: 'Aplicar código de cupón',
        fr: 'Appliquer le code promo',
        it: 'Applica codice coupon',
        ja: 'クーポンコードを適用',
        ko: '쿠폰 코드 적용',
        nl: 'Couponcode toepassen',
        no: 'Bruk kupongkode',
        pl: 'Zastosuj kod kuponu',
        pt_BR: 'Aplicar código do cupom',
        sv: 'Tillämpa kupongkod',
        da: 'Anvend kuponkode',
        fi: 'Käytä kuponkikoodia',
        zh_CN: '应用优惠券代码',
        zh_TW: '套用優惠券代碼',
    },

    couponInputAriaLabel: {
        en_US: 'Coupon code',
        en_GB: 'Coupon code',
        en: 'Coupon code',
        de: 'Gutscheincode',
        es: 'Código de cupón',
        fr: 'Code promo',
        it: 'Codice coupon',
        ja: 'クーポンコード',
        ko: '쿠폰 코드',
        nl: 'Couponcode',
        no: 'Kupongkode',
        pl: 'Kod kuponu',
        pt_BR: 'Código do cupom',
        sv: 'Kupongkod',
        da: 'Kuponkode',
        fi: 'Kuponkikoodi',
        zh_CN: '优惠券代码',
        zh_TW: '優惠券代碼',
    },
};
