export const NOTIFYCHECKOUT = 'NOTIFYCHECKOUT';
export const LOADCHECKOUT = 'LOADCHECKOUT';
export const ENSURELOADED = 'ENSURELOADED';
export const WAITFORCHECKOUT = 'WAITFORCHECKOUT';
export const UPDATEGUESTEMAIL = 'UPDATEGUESTEMAIL';
export const PAYMENTCLIENTREQUEST = 'PAYMENTCLIENTREQUEST';

export const CREATECONTACTPOINTADDRESS = 'CREATECONTACTPOINTADDRESS';
export const UPDATECONTACTPOINTADDRESS = 'UPDATECONTACTPOINTADDRESS';
