/*
 * Copyright (c) 2025, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * For full license text, see the LICENSE file in the repo
 * root or https://opensource.org/licenses/apache-2.0/
 */

/*
 * @description Label data with multi-locale support for dynamicContentRenderer
 */

// Label data with multi-locale support
export const LABEL_DATA = {
    // TextMessage Labels
    TextMessage_productSelection: {
        en_US: 'Show me details about {0} ({1})',
        en_GB: 'Show me details about {0} ({1})',
        en: 'Show me details about {0} ({1})',
        de: 'Zeig mir Details zu {0} ({1})',
        es: 'Muéstrame detalles sobre {0} ({1})',
        fr: 'Montre-moi les détails sur {0} ({1})',
        it: 'Mostrami i dettagli su {0} ({1})',
        ja: '{0} の詳細を表示（{1}）',
        ko: '{0}에 대한 자세한 정보를 보여줘 ({1})',
        nl: 'Toon me details over {0} ({1})',
        no: 'Vis meg detaljer om {0} ({1})',
        pl: 'Pokaż mi szczegóły dotyczące {0} ({1})',
        pt_BR: 'Mostre-me detalhes sobre {0} ({1})',
        sv: 'Visa mig detaljer om {0} ({1})',
        da: 'Vis mig detaljer om {0} ({1})',
        fi: 'Näytä minulle tiedot kohteesta {0} ({1})',
        zh_CN: '显示 {0} 的详细信息（{1}）',
        zh_TW: '顯示 {0} 的詳細資訊（{1}）',
    },

    TextMessage_addProductToCart: {
        en_US: 'Add {0} with {1} in a quantity of {2} to cart ({3})',
        en_GB: 'Add {0} with {1} in a quantity of {2} to cart ({3})',
        en: 'Add {0} with {1} in a quantity of {2} to cart ({3})',
        de: 'Füge {0} mit {1} in der Menge {2} zum Warenkorb hinzu ({3})',
        es: 'Agrega {0} con {1} en una cantidad de {2} al carrito ({3})',
        fr: 'Ajouter {0} avec {1} en quantité de {2} au panier ({3})',
        it: 'Aggiungi {0} con {1} in quantità {2} al carrello ({3})',
        ja: '{1} を指定した {0} を {2} 個カートに追加（{3}）',
        ko: '{1}이(가) 포함된 {0}을(를) {2}개 장바구니에 추가 ({3})',
        nl: 'Voeg {0} met {1} in een hoeveelheid van {2} toe aan de winkelwagen ({3})',
        no: 'Legg {0} med {1} i antall {2} i handlekurven ({3})',
        pl: 'Dodaj {0} z {1} w ilości {2} do koszyka ({3})',
        pt_BR: 'Adicionar {0} com {1} na quantidade de {2} ao carrinho ({3})',
        sv: 'Lägg till {0} med {1} i antal {2} i varukorgen ({3})',
        da: 'Tilføj {0} med {1} i antal {2} til kurven ({3})',
        fi: 'Lisää {0}, jossa {1}, määrää {2} ostoskoriin ({3})',
        zh_CN: '将 {0}（{1}）以数量 {2} 加入购物车（{3}）',
        zh_TW: '將 {0}（{1}）以數量 {2} 加入購物車（{3}）',
    },

    TextMessage_addProductToCartWithNoVariations: {
        en_US: 'Add {0} to cart ({1})',
        en_GB: 'Add {0} to cart ({1})',
        en: 'Add {0} to cart ({1})',
        de: 'Füge {0} zum Warenkorb hinzu ({1})',
        es: 'Agrega {0} al carrito ({1})',
        fr: 'Ajouter {0} au panier ({1})',
        it: 'Aggiungi {0} al carrello ({1})',
        ja: '{0} をカートに追加（{1}）',
        ko: '{0}을(를) 장바구니에 추가 ({1})',
        nl: 'Voeg {0} toe aan de winkelwagen ({1})',
        no: 'Legg {0} i handlekurven ({1})',
        pl: 'Dodaj {0} do koszyka ({1})',
        pt_BR: 'Adicionar {0} ao carrinho ({1})',
        sv: 'Lägg till {0} i varukorgen ({1})',
        da: 'Føj {0} til kurven ({1})',
        fi: 'Lisää {0} ostoskoriin ({1})',
        zh_CN: '将 {0} 加入购物车（{1}）',
        zh_TW: '將 {0} 加入購物車（{1}）',
    },

    TextMessage_applyCouponCode: {
        en_US: 'Apply coupon code {0}',
        en_GB: 'Apply coupon code {0}',
        en: 'Apply coupon code {0}',
        de: 'Gutscheincode {0} anwenden',
        es: 'Aplicar código de cupón {0}',
        fr: 'Appliquer le code de coupon {0}',
        it: 'Applica il codice coupon {0}',
        ja: 'クーポンコード {0} を適用',
        ko: '쿠폰 코드 {0} 적용',
        nl: 'Couponcode {0} toepassen',
        no: 'Bruk kupongkode {0}',
        pl: 'Zastosuj kod kuponu {0}',
        pt_BR: 'Aplicar código de cupom {0}',
        sv: 'Använd kupongkod {0}',
        da: 'Anvend kuponkode {0}',
        fi: 'Käytä kuponkikoodia {0}',
        zh_CN: '应用优惠券代码 {0}',
        zh_TW: '套用優惠券代碼 {0}',
    },

    TextMessage_invalidResponseMessage: {
        en_US: 'I did not understand your response. Please try again.',
        en_GB: 'I did not understand your response. Please try again.',
        en: 'I did not understand your response. Please try again.',
        de: 'Ich habe Ihre Antwort nicht verstanden. Bitte versuchen Sie es erneut.',
        es: 'No entendí tu respuesta. Por favor, inténtalo de nuevo.',
        fr: "Je n'ai pas compris votre réponse. Veuillez réessayer.",
        it: 'Non ho capito la tua risposta. Riprova.',
        ja: 'ご回答が理解できませんでした。もう一度お試しください。',
        ko: '응답을 이해하지 못했습니다. 다시 시도해 주세요.',
        nl: 'Ik begreep uw antwoord niet. Probeer het opnieuw.',
        no: 'Jeg forstod ikke svaret ditt. Prøv igjen.',
        pl: 'Nie zrozumiałem Twojej odpowiedzi. Spróbuj ponownie.',
        pt_BR: 'Não entendi sua resposta. Tente novamente.',
        sv: 'Jag förstod inte ditt svar. Försök igen.',
        da: 'Jeg forstod ikke dit svar. Prøv igen.',
        fi: 'En ymmärtänyt vastaustasi. Yritä uudelleen.',
        zh_CN: '我没有理解你的回复。请再试一次。',
        zh_TW: '我未能理解您的回覆。請再試一次。',
    },

    // Show More Products Labels
    TextMessage_showMoreProducts: {
        en_US: 'Show more',
        en_GB: 'Show more',
        en: 'Show more',
        de: 'Mehr anzeigen',
        es: 'Mostrar más',
        fr: 'Afficher plus',
        it: 'Mostra altro',
        ja: 'もっと表示',
        ko: '더 보기',
        nl: 'Meer tonen',
        no: 'Vis flere',
        pl: 'Pokaż więcej',
        pt_BR: 'Mostrar mais',
        sv: 'Visa fler',
        da: 'Vis flere',
        fi: 'Näytä lisää',
        zh_CN: '显示更多',
        zh_TW: '顯示更多',
    },

    // Common Payment Labels
    Common_Payment_Completed: {
        en_US: 'Paid with {0}',
        en_GB: 'Paid with {0}',
        en: 'Paid with {0}',
        de: 'Bezahlt mit {0}',
        es: 'Pagado con {0}',
        fr: 'Payé avec {0}',
        it: 'Pagato con {0}',
        ja: '{0} で支払い済み',
        ko: '{0}로 결제 완료',
        nl: 'Betaald met {0}',
        no: 'Betalt med {0}',
        pl: 'Zapłacono przy użyciu {0}',
        pt_BR: 'Pago com {0}',
        sv: 'Betalat med {0}',
        da: 'Betalt med {0}',
        fi: 'Maksettu {0}:lla',
        zh_CN: '使用 {0} 付款',
        zh_TW: '使用 {0} 付款',
    },

    Common_Payment_Failed: {
        en_US: '{0} failed',
        en_GB: '{0} failed',
        en: '{0} failed',
        de: '{0} fehlgeschlagen',
        es: '{0} falló',
        fr: 'Échec de {0}',
        it: '{0} non riuscito',
        ja: '{0} に失敗しました',
        ko: '{0} 실패',
        nl: '{0} is mislukt',
        no: '{0} mislyktes',
        pl: '{0} nie powiodło się',
        pt_BR: '{0} falhou',
        sv: '{0} misslyckades',
        da: '{0} mislykkedes',
        fi: '{0} epäonnistui',
        zh_CN: '{0} 失败',
        zh_TW: '{0} 失敗',
    },

    Common_Payment_Canceled: {
        en_US: '{0} was canceled',
        en_GB: '{0} was cancelled',
        en: '{0} was canceled',
        de: '{0} wurde abgebrochen',
        es: '{0} fue cancelado',
        fr: '{0} a été annulé',
        it: '{0} è stato annullato',
        ja: '{0} はキャンセルされました',
        ko: '{0}이(가) 취소되었습니다',
        nl: '{0} is geannuleerd',
        no: '{0} ble avbrutt',
        pl: '{0} został anulowany',
        pt_BR: '{0} foi cancelado',
        sv: '{0} avbröts',
        da: '{0} blev annulleret',
        fi: '{0} peruttiin',
        zh_CN: '{0} 已取消',
        zh_TW: '{0} 已取消',
    },

    Common_Payment_Succeeded_NoPaymentMethod: {
        en_US: 'Payment succeeded',
        en_GB: 'Payment succeeded',
        en: 'Payment succeeded',
        de: 'Zahlung erfolgreich',
        es: 'Pago exitoso',
        fr: 'Paiement réussi',
        it: 'Pagamento riuscito',
        ja: '支払いに成功しました',
        ko: '결제가 성공했습니다',
        nl: 'Betaling geslaagd',
        no: 'Betaling vellykket',
        pl: 'Płatność zakończona pomyślnie',
        pt_BR: 'Pagamento realizado com sucesso',
        sv: 'Betalning lyckades',
        da: 'Betaling lykkedes',
        fi: 'Maksu onnistui',
        zh_CN: '付款成功',
        zh_TW: '付款成功',
    },

    Common_Payment_Failed_NoPaymentMethod: {
        en_US: 'Payment failed',
        en_GB: 'Payment failed',
        en: 'Payment failed',
        de: 'Zahlung fehlgeschlagen',
        es: 'Pago fallido',
        fr: 'Échec du paiement',
        it: 'Pagamento non riuscito',
        ja: '支払いに失敗しました',
        ko: '결제 실패',
        nl: 'Betaling mislukt',
        no: 'Betaling mislyktes',
        pl: 'Płatność nie powiodła się',
        pt_BR: 'Pagamento falhou',
        sv: 'Betalningen misslyckades',
        da: 'Betaling mislykkedes',
        fi: 'Maksu epäonnistui',
        zh_CN: '付款失败',
        zh_TW: '付款失敗',
    },

    Common_DynamicContent_Region_Aria_Label: {
        en_US: 'Dynamic content region',
        en_GB: 'Dynamic content region',
        en: 'Dynamic content region',
        de: 'Bereich für dynamische Inhalte',
        es: 'Región de contenido dinámico',
        fr: 'Région de contenu dynamique',
        it: 'Area contenuto dinamico',
        ja: '動的コンテンツ領域',
        ko: '동적 콘텐츠 영역',
        nl: 'Regio met dynamische inhoud',
        no: 'Område for dynamisk innhold',
        pl: 'Obszar treści dynamicznych',
        pt_BR: 'Região de conteúdo dinâmico',
        sv: 'Område för dynamiskt innehåll',
        da: 'Område for dynamisk indhold',
        fi: 'Dynaamisen sisällön alue',
        zh_CN: '动态内容区域',
        zh_TW: '動態內容區域',
    },

    Common_DynamicContent_RichText_Region_Aria_Label: {
        en_US: 'Rich text message content',
        en_GB: 'Rich text message content',
        en: 'Rich text message content',
        de: 'Rich-Text-Nachrichteninhalt',
        es: 'Contenido del mensaje de texto enriquecido',
        fr: 'Contenu du message texte enrichi',
        it: 'Contenuto del messaggio di testo formattato',
        ja: 'リッチテキストメッセージの内容',
        ko: '서식 있는 텍스트 메시지 콘텐츠',
        nl: 'Rich-text-berichtinhoud',
        no: 'Riktekst-meldingsinnhold',
        pl: 'Zawartość wiadomości w formacie Rich Text',
        pt_BR: 'Conteúdo da mensagem em rich text',
        sv: 'Innehåll i rich text-meddelande',
        da: 'Indhold af rich text-besked',
        fi: 'Rich text -viestin sisältö',
        zh_CN: '富文本消息内容',
        zh_TW: '豐富文字訊息內容',
    },

    Common_DynamicContent_Contextual_Description: {
        en_US: 'Let me know who you are shopping for and what’s the occasion, or choose from the suggestions below.',
        en_GB: 'Let me know who you’re shopping for and what the occasion is, or pick from the suggestions below.',
        en: 'Let me know who you are shopping for and what’s the occasion, or choose from the suggestions below.',
        de: 'Teilen Sie mir mit, für wen Sie einkaufen und zu welchem Anlass, oder wählen Sie aus den Vorschlägen unten.',
        es: 'Dime para quién estás comprando y cuál es la ocasión, o elige entre las sugerencias de abajo.',
        fr: 'Indiquez pour qui vous faites vos achats et pour quelle occasion, ou choisissez parmi les suggestions ci-dessous.',
        it: 'Dimmi per chi stai facendo acquisti e per quale occasione, oppure scegli tra i suggerimenti qui sotto.',
        ja: 'どなたへのお買い物か、どんな用途かを教えてください。下の候補から選ぶこともできます。',
        ko: '누구를 위해 쇼핑하는지와 어떤 행사인지 알려주세요. 아래 제안에서 선택할 수도 있습니다.',
        nl: 'Laat me weten voor wie je shopt en voor welke gelegenheid, of kies uit de suggesties hieronder.',
        no: 'Fortell hvem du handler for og til hvilken anledning, eller velg fra forslagene nedenfor.',
        pl: 'Powiedz, dla kogo robisz zakupy i z jakiej okazji, albo wybierz jedną z poniższych sugestii.',
        pt_BR: 'Diga para quem você está comprando e para qual ocasião, ou escolha entre as sugestões abaixo.',
        sv: 'Berätta vem du handlar till och för vilket tillfälle, eller välj bland förslagen nedan.',
        da: 'Fortæl, hvem du køber til, og i hvilken anledning, eller vælg blandt forslagene nedenfor.',
        fi: 'Kerro kenelle olet ostamassa ja mikä on tilaisuus, tai valitse alla olevista ehdotuksista.',
        zh_CN: '告诉我您要为谁购物、是什么场合，也可以从下方建议中选择。',
        zh_TW: '告訴我您要為誰購物及場合為何，或從下方建議中選擇。',
    },

    // Apple Pay specific labels
    Common_ApplePay_paymentFailed: {
        en_US: "I couldn't process Apple Pay. Try again.",
        en_GB: "I couldn't process Apple Pay. Try again.",
        en: "I couldn't process Apple Pay. Try again.",
        de: 'Ich konnte Apple Pay nicht verarbeiten. Bitte versuch es erneut.',
        es: 'No pude procesar Apple Pay. Inténtalo de nuevo.',
        fr: 'Impossible de traiter Apple Pay. Réessayez.',
        it: 'Non sono riuscito a elaborare Apple Pay. Riprova.',
        ja: 'Apple Pay を処理できませんでした。もう一度お試しください。',
        ko: 'Apple Pay를 처리할 수 없었습니다. 다시 시도해 주세요.',
        nl: 'Ik kon Apple Pay niet verwerken. Probeer het opnieuw.',
        no: 'Jeg kunne ikke behandle Apple Pay. Prøv igjen.',
        pl: 'Nie udało mi się przetworzyć Apple Pay. Spróbuj ponownie.',
        pt_BR: 'Não consegui processar o Apple Pay. Tente novamente.',
        sv: 'Kunde inte behandla Apple Pay. Försök igen.',
        da: 'Jeg kunne ikke behandle Apple Pay. Prøv igen.',
        fi: 'En voinut käsitellä Apple Payta. Yritä uudelleen.',
        zh_CN: '无法处理 Apple Pay。请重试。',
        zh_TW: '無法處理 Apple Pay。請再試一次。',
    },

    Common_ApplePay_paymentCanceled: {
        en_US: 'Apple Pay was canceled',
        en_GB: 'Apple Pay was cancelled',
        en: 'Apple Pay was canceled',
        de: 'Apple Pay wurde abgebrochen',
        es: 'Apple Pay fue cancelado',
        fr: 'Apple Pay a été annulé',
        it: 'Apple Pay è stato annullato',
        ja: 'Apple Pay はキャンセルされました',
        ko: 'Apple Pay가 취소되었습니다',
        nl: 'Apple Pay is geannuleerd',
        no: 'Apple Pay ble avbrutt',
        pl: 'Apple Pay został anulowany',
        pt_BR: 'Apple Pay foi cancelado',
        sv: 'Apple Pay avbröts',
        da: 'Apple Pay blev annulleret',
        fi: 'Apple Pay peruttiin',
        zh_CN: 'Apple Pay 已取消',
        zh_TW: 'Apple Pay 已取消',
    },

    Common_ApplePay_paymentCompleted: {
        en_US: 'Paid with Apple Pay',
        en_GB: 'Paid with Apple Pay',
        en: 'Paid with Apple Pay',
        de: 'Mit Apple Pay bezahlt',
        es: 'Pagado con Apple Pay',
        fr: 'Payé avec Apple Pay',
        it: 'Pagato con Apple Pay',
        ja: 'Apple Pay で支払い済み',
        ko: 'Apple Pay로 결제 완료',
        nl: 'Betaald met Apple Pay',
        no: 'Betalt med Apple Pay',
        pl: 'Zapłacono Apple Pay',
        pt_BR: 'Pago com Apple Pay',
        sv: 'Betalat med Apple Pay',
        da: 'Betalt med Apple Pay',
        fi: 'Maksettu Apple Paylla',
        zh_CN: '使用 Apple Pay 付款',
        zh_TW: '使用 Apple Pay 付款',
    },
};
