export const SAMPLE_DATA = {
    adjustmentAggregates: {
        available: false,
        status: 'Submitted',
        totalDeliveryPromotionDistAmount: null,
        totalDeliveryPromotionLineAmount: null,
        totalDeliveryPromotionTotalAmount: null,
        totalProductPromotionDistAmount: null,
        totalProductPromotionLineAmount: null,
        totalProductPromotionTotalAmount: null,
    },
    createdDate: '2022-09-28T11:16:15.000Z',
    currencyIsoCode: 'USD',
    fields: {
        TotalAdjustedDeliveryAmount: {
            dataName: 'TotalAdjustedDeliveryAmount',
            dataType: 'xsd:double',
            label: 'Shipping',
            text: '9.99',
            type: 'currency',
        },
        TotalDeliveryAdjDistAmount: {
            dataName: 'TotalDeliveryAdjDistAmount',
            dataType: 'xsd:double',
            label: 'Order Shipping Adjustments',
            text: '-1.0',
            type: 'currency',
        },
        TotalAdjustedProductTaxAmount: {
            dataName: 'TotalAdjustedProductTaxAmount',
            dataType: 'xsd:double',
            label: 'Subtotal Tax',
            text: '4.86',
            type: 'currency',
        },
        TaxLocaleType: {
            dataName: 'TaxLocaleType',
            dataType: 'xsd:string',
            label: 'Tax Locale Type',
            text: 'Net',
            type: 'picklist',
        },
        TotalDeliveryAmount: {
            dataName: 'TotalDeliveryAmount',
            dataType: 'xsd:double',
            label: 'Shipping Subtotal',
            text: '11.99',
            type: 'currency',
        },
        TotalProductAdjDistAmtWithTax: {
            dataName: 'TotalProductAdjDistAmtWithTax',
            dataType: 'xsd:double',
            label: 'Order Product Adjustments with Tax',
            text: '-2.21',
            type: 'currency',
        },
        TotalAdjustedProductAmount: {
            dataName: 'TotalAdjustedProductAmount',
            dataType: 'xsd:double',
            label: 'Subtotal',
            text: '53.11',
            type: 'currency',
        },
        TotalTaxAmount: {
            dataName: 'TotalTaxAmount',
            dataType: 'xsd:double',
            label: 'Tax',
            text: '6.92',
            type: 'currency',
        },
        TotalDeliveryAdjDistTaxAmount: {
            dataName: 'TotalDeliveryAdjDistTaxAmount',
            dataType: 'xsd:double',
            label: 'Order Shipping Adjustments Tax',
            text: '0.2',
            type: 'currency',
        },
        TotalProductAdjDistTaxAmount: {
            dataName: 'TotalProductAdjDistTaxAmount',
            dataType: 'xsd:double',
            label: 'Order Product Adjustments Tax',
            text: '0.5',
            type: 'currency',
        },
        TotalAdjProductAmtWithTax: {
            dataName: 'TotalAdjProductAmtWithTax',
            dataType: 'xsd:double',
            label: 'Subtotal with Tax',
            text: '57.97',
            type: 'currency',
        },
        TotalProductAmount: {
            dataName: 'TotalProductAmount',
            dataType: 'xsd:double',
            label: 'Product Subtotal',
            text: '57.0',
            type: 'currency',
        },
        TotalProductTaxAmount: {
            dataName: 'TotalProductTaxAmount',
            dataType: 'xsd:double',
            label: 'Product Subtotal Tax',
            text: '4.56',
            type: 'currency',
        },
        TotalAmount: {
            dataName: 'TotalAmount',
            dataType: 'xsd:double',
            label: 'Pretax Subtotal',
            text: '59.39',
            type: 'currency',
        },
        GrandTotalAmount: {
            dataName: 'GrandTotalAmount',
            dataType: 'xsd:double',
            label: 'Total',
            text: '66.31',
            type: 'currency',
        },
        CurrencyIsoCode: {
            dataName: 'CurrencyIsoCode',
            dataType: 'xsd:string',
            label: 'Currency ISO Code',
            text: 'USD',
            type: 'picklist',
        },
        TotalAdjDistTaxAmount: {
            dataName: 'TotalAdjDistTaxAmount',
            dataType: 'xsd:double',
            label: 'Order Adjustments Tax',
            text: '0.7',
            type: 'currency',
        },
        TotalAdjDeliveryAmtWithTax: {
            dataName: 'TotalAdjDeliveryAmtWithTax',
            dataType: 'xsd:double',
            label: 'Shipping with Tax',
            text: '11.35',
            type: 'currency',
        },
        TotalAdjDistAmountWithTax: {
            dataName: 'TotalAdjDistAmountWithTax',
            dataType: 'xsd:double',
            label: 'Order Adjustments with Tax',
            text: '-3.01',
            type: 'currency',
        },
        TotalProductAdjDistAmount: {
            dataName: 'TotalProductAdjDistAmount',
            dataType: 'xsd:double',
            label: 'Order Product Adjustments',
            text: '-2.71',
            type: 'currency',
        },
        TotalProductAmountWithTax: {
            dataName: 'TotalProductAmountWithTax',
            dataType: 'xsd:double',
            label: 'Product Subtotal With Tax',
            text: '61.56',
            type: 'currency',
        },
        TotalDeliveryTaxAmount: {
            dataName: 'TotalDeliveryTaxAmount',
            dataType: 'xsd:double',
            label: 'Shipping Subtotal Tax',
            text: '0.96',
            type: 'currency',
        },
        TotalDeliveryAdjDistAmtWithTax: {
            dataName: 'TotalDeliveryAdjDistAmtWithTax',
            dataType: 'xsd:double',
            label: 'Order Shipping Adjustments with Tax',
            text: '-0.8',
            type: 'currency',
        },
        TotalDeliveryAmountWithTax: {
            dataName: 'TotalDeliveryAmountWithTax',
            dataType: 'xsd:double',
            label: 'Shipping Subtotal With Tax',
            text: '12.95',
            type: 'currency',
        },
        TotalAdjDistAmount: {
            dataName: 'TotalAdjDistAmount',
            dataType: 'xsd:double',
            label: 'Order Adjustments',
            text: '-3.71',
            type: 'currency',
        },
        TotalAdjustedDeliveryTaxAmount: {
            dataName: 'TotalAdjustedDeliveryTaxAmount',
            dataType: 'xsd:double',
            label: 'Shipping Tax',
            text: '1.36',
            type: 'currency',
        },
    },
    orderNumber: 'HOFZA-U53TZ-B53AP-5FMLQ',
    orderSummaryId: '1OsOG00000002f00AA',
    orderedDate: '2022-09-28T11:16:14.000Z',
    ownerId: '005OG000000ab3cYAA',
    status: 'Created',
    totalAmount: '59.39',
};
