# This workflow will do a clean installation of node dependencies,
# cache/restore them, build the source code, verify the code conformance,
# and run tests across different versions of node.
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: GitHub Traffic Data Retrieval

on:
    schedule:
        - cron: '0 0/12 * * *'
          # Cron job at minute 0 past every 12th hour from 0 through 23, i.e. every midnight and noon

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: gh-traffic
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run gh:traffic
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  GIST_ID_CLONES: ${{ secrets.GIST_ID_CLONES }}
                  GIST_ID_POPULAR_PATHS: ${{ secrets.GIST_ID_POPULAR_PATHS }}
                  GIST_ID_POPULAR_REFERRERS: ${{ secrets.GIST_ID_POPULAR_REFERRERS }}
